[database]
dsn = "root:123456@tcp(localhost:3306)/alert-service?charset=utf8mb4&parseTime=True&loc=Local"
# max open connections
maxOpenConn = 200
# max idle connections
maxIdleConn = 100
# unit: s
# The maximum time a connection can be reused
maxLifeTime = 5000
#
maxIdleTime = 5000
